In [1]:
from pytrends.request import TrendReq
import pandas as pd

In [2]:
pytrends = TrendReq(
    hl='en-US',
    tz=360
)

keywords = [
    "Rolex Daytona",
    "Rolex Submariner",
    "Rolex GMT-Master II"
]

pytrends.build_payload(
    kw_list=keywords,
    timeframe='today 12-m'
)

df_trends = pytrends.interest_over_time()

df_trends.head()

/Users/jingshi/.pyenv/versions/Artefact/lib/python3.11/site-packages/pytrends/request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

            Rolex Daytona  Rolex Submariner  Rolex GMT-Master II  isPartial
date
2025-05-18             27                27                    1      False
2025-05-25             32                28                    1      False
2025-06-01             35                31                    1      False
2025-06-08             36                34                    1      False
2025-06-15             33                30                    1      False

In [3]:
if "isPartial" in df_trends.columns:
    df_trends = df_trends.drop(columns=["isPartial"])

df_trends.to_csv(
    "../data/processed/google_trends_rolex.csv"
)

print("Saved to ../data/processed/google_trends_rolex.csv")

Saved to ../data/processed/google_trends_rolex.csv

In [4]:
df_trends.describe()

       Rolex Daytona  Rolex Submariner  Rolex GMT-Master II
count      54.000000         54.000000            54.000000
mean       40.481481         43.259259             3.574074
std         7.944954         20.227186             2.765023
min        27.000000         27.000000             1.000000
25%        35.000000         32.000000             2.250000
50%        38.000000         34.000000             3.000000
75%        44.000000         40.000000             4.000000
max        67.000000        100.000000            15.000000